### ISSUE TITLE
Demasiadas excepciones. Revísalas

### ISSUE THREAD

**Issue by lmagarin** [Javierfs94/ExamenPGNSegundoTrimestre#1]
https://github.com/Javierfs94/ExamenPGNSegundoTrimestre/blob/66d5c7280b53f8f0348708b259eb7321c937e1df/exJavierFriasSerranoJava/src/ejercicio1/exceptions/StockNegativoExceptions.java#L5

Si organizas las excepciones en paquetes deben estar donde se lanzan

**Comment by Javierfs94** [comment]
Al revisar las excepciones vi que se habían duplicado. Si no era eso a lo que se refería, vuelva a abrirme el issue he indíquemeel error. Muchas gracias :)

**Comment by lmagarin** [comment]
El paquete exception debe estar dentro del almacén. Si organizas las excepciones en paquetes deben estar donde se lanzan
